dots-install and sysm: cleanup and conversion from HTTPS to SSH installation

diff --git a/dots-install b/dots-install
--- a/dots-install
+++ b/dots-install
@@ -1,7 +1,7 @@
 #!/usr/bin/env sh
 #
 # A script for bootstrapping my dotfiles installation.
-# Still very incomplete.
+# On early stages.
 
 PROG=$(basename $0)
 
@@ -11,9 +11,12 @@ exists() {
 
 usage() {
   printf >&2 "%s: %s\n" "$PROG" "installs dotfiles" # terrible description
-  printf >&2 "Usage: %s\n" "$PROG <SOURCE> <DEST>"
+  printf >&2 "Usage: %s\n" "$PROG <ACTION> <DEST>"
   printf >&2 "Where\n"
-  printf >&2 "    SOURCE := { https | ssh }\n"
+  printf >&2 "    ACTION : the action to be done.\n"
+  printf >&2 "           | https: download to DEST via HTTPS\n"
+  printf >&2 "           | ssh: download to DEST via SSH\n"
+  printf >&2 "           | https-to-ssh: download to (already existing, but https-based) DEST via SSH (thus converting it to SSH)\n"
   printf >&2 "    DEST   :  the path where the dotfiles will be installed."
   exit 1
 }
@@ -22,9 +25,9 @@ usage() {
 
 case "$1" in
   https) DOTFILES_URL="https://github.com/YohananDiamond/dotfiles" ;;
-  ssh) DOTFILES_URL="git@github.com:yohanandiamond/dotfiles" ;;
+  ssh|https-to-ssh) DOTFILES_URL="git@github.com:yohanandiamond/dotfiles" ;;
   *)
-    printf >&2 "Invalid SOURCE: %s\n" "$1"
+    printf >&2 "Invalid ACTION: %s\n" "$1"
     printf >&2 "\n"
     usage
     ;;
@@ -52,6 +55,24 @@ for dependency in git python3; do
   fi
 done
 
-git clone "$DOTFILES_URL" "$2" \
-  && (cd "$2" && git checkout experimental) \
-  && DOTFILES="$2" "$2/scripts/sysm"
+case "$1" in
+  https-to-ssh)
+    if [ ! -d "$2" ]; then
+      printf >&2 "%s is not a directory.\n" "$2"
+      exit 1
+    fi
+    temp=$(mktemp) \
+      && rm -f "$temp" \
+      && mv "$2" "$temp" || exit 1
+    if git clone "$DOTFILES_URL" "$2"; then
+      rm -rf "$temp"
+    else
+      mv "$temp" "$2"
+    fi
+    ;;
+  *) 
+    git clone "$DOTFILES_URL" "$2" \
+      && (cd "$2" && git checkout experimental) \
+      && DOTFILES="$2" "$2/scripts/sysm"
+    ;;
+esac
