Only show symlink output if an error ocurred.

diff --git a/sync b/sync
--- a/sync
+++ b/sync
@@ -53,7 +53,6 @@ lf() {
     local NEW_FILE="${2}"
 
     mkdir -p "$(dirname "${NEW_FILE}")"
-    echo "'${ORIGINAL_FILE}' -> '${NEW_FILE}'"
 
     # TODO: cancel if ${ORIGINAL_FILE} doesn't exist.
 
@@ -64,7 +63,7 @@ lf() {
         mv "${NEW_FILE}" -t "${BACKUP_FILE_PATH}"
     fi
 
-    ln -s "${ORIGINAL_FILE}" "${NEW_FILE}"
+    ln -s "${ORIGINAL_FILE}" "${NEW_FILE}" || echo "The error above ocurred while symlinking '${ORIGINAL_FILE}' -> '${NEW_FILE}'"
 }
 
 lf_glob() {
