Many more changes:
* New category - Patch: files in the ./patches folder are patches that
should be (manually, at the moment) applied.

* Patch#xdg-opener: a patch for xdg-open to use Script#open before
anything, if said script wasn't launched by xdg-open itself.

* Script#open: patches to support Patch#xdg-opener and some other minor
changes.

* Bspwm: added Sxiv rule.

* Neovim: made MyFoldText() more flexible; added CleanWhitespace
command; removed default general textwidth; added some configs to
filetypes bash, zsh, vim, rust; added lambda quick insert mapping (C-l l
-> λ); made more patches on highlighting.

* Neovim#rifle: added bspc-related things (they are not working, but I'm
too lazy to remove it again. I'll remake this plugin in vimscript soon,
anyways).

* Script#atdir: for now it just opens broot on a directory, but I plan
to do more things later to replace the inspect-dir function on zsh and
Script#git-check.

* Sxhkd: changed & simplified bindings.

* Script#imgclip: new script to copy images to clipboard.

* Sxiv: added config and keybinding to Script#imgclip.

* Script#flamew: previously called flamewrapper, it is now slightly more
concise and organized.

* Script#runread: made the code more modular and added support for
another command (R for re-run).

* Lib#ystd.sh: made the exists() function more POSIX-y.

* Share#env.sh: added a value for XDG_CURRENT_DESKTOP; added flags -RC
for less.

* Minor changes on: Emacs, mimeapps.list, Meta#dotsync, Broot.

diff --git a/local/bin/flamew b/local/bin/flamew
--- a/local/bin/flamew
+++ b/local/bin/flamew
@@ -1,17 +1,18 @@
 #!/usr/bin/env sh
 
 source ~/.local/lib/ystd.sh
-depCheck flameshot
+depCheck flameshot date
 
 if [ $# != 1 ]; then
-  printf >&2 "%s\n" "Usage: $(basename $0) {gui | full | fullc}"
+  printf >&2 "%s\n" "Usage: $(basename $0) { gui | full | fullc }"
   exit 1
 fi
 
-folder="${FLAMEDASH_SCR_FOLDER:-~/.cache/screenshots}"
+BASE_FOLDER="${FLAMEDASH_SCR_FOLDER:-~/.cache/screenshots}"
+folder="$BASE_FOLDER/$(date +%Y-%m)"
 
 if ! mkdir -p "$folder"; then
-  printf >&2 "%s\n" "Could not make directory $folder" \
+  printf >&2 "%s\n" "Could not make directory $folder"
   exit 1
 fi
 
