Monthly patches, part one

diff --git a/local/bin/flamedash b/local/bin/flamedash
--- a/local/bin/flamedash
+++ b/local/bin/flamedash
@@ -1,32 +1,22 @@
 #!/usr/bin/env sh
 
-PROG="$(basename $0)"
-
-msg() {
-  if [ -t 1 ]; then
-    echo "$@"
-  else
-    notify-send "$@"
-  fi
-}
-
 if [ $# != 1 ]; then
-  msg "$PROG: There should be at least one argument."
+  printf >&2 "%s\n" "There should be at least one argument."
   exit 1
 fi
 
 if [ -z "$FLAMEDASH_SCR_FOLDER" ]; then
-  msg "$PROG: please specify \$FLAMEDASH_SCR_FOLDER with the path to the screenshot."
+  printf >&2 "%s\n" "Please specify \$FLAMEDASH_SCR_FOLDER with the path to the screenshot."
   exit 1
 fi
 
 if ! type flameshot >/dev/null 2>/dev/null; then
-  msg "$PROG: command 'flameshot' not found. please make sure it is on your \$PATH."
+  printf >&2 "%s\n" "Command 'flameshot' not found. please make sure it is on your \$PATH."
   exit 1
 fi
 
 if ! mkdir -p "$FLAMEDASH_SCR_FOLDER"; then
-  msg "$PROG: could not make directory $FLAMEDASH_SCR_FOLDER."
+  printf >&2 "%s\n" "Could not make directory $FLAMEDASH_SCR_FOLDER."
 fi
 
 case "$1" in
@@ -35,7 +25,7 @@ case "$1" in
   full) flameshot full -p "$FLAMEDASH_SCR_FOLDER" ;;
   fullc) flameshot full -c ;;
   *)
-    msg "$PROG: invalid command."
+    printf >&2 "%s\n" "Invalid command."
     exit 1
     ;;
 esac
