Monthly patch - the biggest part
Changed a lot of things, mostly scripts. Too lazy to make a complete
list.

diff --git a/local/bin/fzarticle b/local/bin/fzarticle
--- a/local/bin/fzarticle
+++ b/local/bin/fzarticle
@@ -3,47 +3,20 @@
 # A script to find and load articles.
 # Works better with fuzzy finders.
 
-case $# in
-  0) 
-    if [ -z "$F_ARTICLES" ]; then
-      echo "Please set \$F_ARTICLES for the articles folder or specify it here as \$1."
-      exit 1
-    fi
-    ARTICLES="$F_ARTICLES"
-    ;;
-  1) ARTICLES="$1" ;;
-  *) 
-    echo "Invalid amount of arguments."
-    exit 1
-    ;;
-esac
+source ~/.local/lib/ystd.sh
+depCheck fd
 
-exists() {
-  [ $# = 1 ] || return 2
-  type "$1" >/dev/null 2>/dev/null
-}
-
-if exists "dmenu"; then
-  if [ -n "$DISPLAY" ]; then
-    choose() { dmenu -l 10 <<<"$1"; }
-  else
-    echo "dmenu was detected, but won't be used due to display not being found."
-    exists "fzf" &&
-      choose() { fzf <<<"$1"; }
-  fi
-elif exists "fzf"; then
-  choose() { fzf <<<"$1"; }
-else
-  echo "No valid fuzzy finder found."
-  echo "The valid ones are: dmenu, fzf"
+if [ $# != 0 ]; then
+  printf >&2 "%s\n" "Usage: $(basename $0) <url>"
+  printf >&2 "%s %s\n" "The articles folder is" '${F_ARTICLES:-~/articles}'
   exit 1
 fi
 
-if [ -z "$DISPLAY" ] && exists "w3m"; then
-  browse() { w3m $@; }
-else
-  browse() { nuke $@; }
+articles="${F_ARTICLES:-~/articles}"
+if ! cd "$articles"; then
+  printf >&2 "%s\n" "Couldn't open $articles"
+  exit 1
 fi
 
-cd "$ARTICLES" || exit 1
-CHOICE="$(choose "$(find . -mindepth 1 -maxdepth 1 | sed 's/^\.\///g' | grep '\.html$')")" && browse "$CHOICE"
+choice="$(fd -d 1 -t f '\.html$' | dmenu)" \
+  && open "$choice"
diff --git a/local/bin/fzpow b/local/bin/fzpow
--- a/local/bin/fzpow
+++ b/local/bin/fzpow
@@ -8,98 +8,62 @@
 # Settings
 I3LOCK_COLOR="282828"
 I3LOCK_IMG="$HOME/.local/share/i3lock-img.png"
-OPTIONS=$'lock\nlogout\nsuspend\nhibernate\nreboot\nshutdown'
+OPTIONS='lock\nlogout\nsuspend\nhibernate\nreboot\nshutdown'
 
-# Check if all dependencies are available
-check_dependencies() { # {{{
-  for dependency in dmenu xdg-screensaver systemctl notify-send; do
-    type "${dependency}" >/dev/null || exit 127
-  done
-} # }}}
+source ~/.local/lib/ystd.sh
+depCheck dmenu systemctl i3lock xdg-screensaver
 
-# Match arguments
-match_args() { # {{{
+fuzzyMatch() { printf "$OPTIONS" | dmenu -p "Power: "; }
+matchArgs() { # {{{
   case $# in
-    0)
-      local f="$(fuzzy_match)"
-      if [ -n "$f" ]; then
-        match_args "$f"
+    0) local choice="$(fuzzyMatch)"
+      if [ -n "$choice" ]; then
+        matchArgs "$choice"
       else
-        show_help
-      fi
-      ;;
+        showHelp
+      fi ;;
 
-    1)
-      case "${1}" in
-        lock) ;;
-        logout) ;;
-        suspend) ;;
-        hibernate) ;;
-        reboot) ;;
-        shutdown) ;;
-        *)
-          show_help
-          ;;
-      esac
-      eval "action_${1}"
-      ;;
+    1) case "$1" in
+        lock|logout|suspend|hibernate|reboot|shutdown) \
+          eval "action_$1" ;;
+        *) showHelp ;;
+      esac ;;
 
-    *)
-      show_help
-      ;;
+    *) showHelp ;;
   esac
 } # }}}
-
-# Fuzzy matching
-fuzzy_match() { # {{{
-  echo "${OPTIONS}" | dmenu -p "Power: "
-} # }}}
-
-# Help
-show_help() { # {{{
-  echo "$(basename "$0"): a simple power menu for i3 and systemd."
-  echo ""
-  echo "Allowed options:"
-  echo "${OPTIONS}" |
-    while read line; do
-      echo "  ${line}"
-    done
-  echo ""
-  echo "If no argument is specified, a dmenu pop-up is shown."
-  exit 2
+showHelp() { # {{{
+  printf >&2 "%s %s\n" "Usage: $(basename $0)" \
+    "[{lock | logout | suspend | hibernate | reboot | shutdown}]"
+  printf >&2 "%s\n" "If no argument is specified, a dmenu pop-up is shown."
+  exit 1
 } # }}}
 
 # Actions
 action_lock() { # {{{
-  if ! xdg-screensaver lock 2>/dev/null; then
     if [ -r "$I3LOCK_IMG" ]; then
       i3lock -i "$I3LOCK_IMG"
     else
       i3lock -c "$I3LOCK_COLOR"
     fi
-  fi
 } # }}}
 action_logout() { # {{{
-  case "${WM}" in
+  case "$WM" in
     i3) i3-msg exit ;;
     bspwm) bspc quit ;;
-    *)
-      local msg="Unknown WM. Please register it in the file source code."
-      echo "$msg"
-      notify-send "$msg" -u critical
-      ;;
+    *) printf 'Unknown wm "%s" - logging out will not work\n' "$wm" ;;
   esac
 } # }}}
 action_suspend() { # {{{
   if action_lock; then
     systemctl suspend
   else
-    notify-send "Failed to suspend." -u critical
+    printf >&2 "Failed to lock - suspending was cancelled\n"
   fi
 } # }}}
 action_hibernate() { # {{{
-  echo "Hibernate: currently disabled."
-  return 3
+  printf >&2 "The hibernate action is currently unimplemented\n"
+  exit 1
 } # }}}
 action_reboot() { # {{{
   systemctl reboot
@@ -108,5 +72,4 @@ action_shutdown() { # {{{
   systemctl poweroff
 } # }}}
 
-check_dependencies
-match_args $@
+matchArgs "$@"
diff --git a/local/bin/git-check b/local/bin/git-check
--- a/local/bin/git-check
+++ b/local/bin/git-check
@@ -1,24 +1,24 @@
 #!/usr/bin/env bash
 
 if [ $# != 1 ]; then
-  echo "Usage: $(basename $0) <repo-path>"
+  printf >&2 "%s\n" "Usage: $(basename $0) <repo-path>"
   exit 1
 fi
 
 cd "$1" || exit
 
 if git status -sb; then
-  echo -en '\e[2 q'
+  printf '\e[2 q'
   while [ -z "$EXIT" ]; do
-    echo -e '::::: [d]iff, [a]dd-commit, [p]ull, pu[s]h, [f]etch, [l]og, [q]uit'
+    printf "%s\n" '::::: [d]iff, [a]dd-commit, [p]ull, pu[s]h, [f]etch, [l]og, [q]uit'
     printf '\e[38;5;11m(git)\e[m λ> '
     read -n1 ch; echo
     case "$ch" in
-      d)
-        git add .
+      d) git add .
         git diff HEAD
         ;;
-      a) git add . && git commit || git reset . ;;
+      a) git add . \
+        && git commit ;;
       l) git log --all --oneline ;;
       p) git pull ;;
       s) git push ;;
@@ -27,13 +27,10 @@ if git status -sb; then
       q) EXIT=0 ;;
       ) EXIT=0 ;;
       "") clear ;;
-      *) echo "Invalid option: \"${ch}\"." ;;
+      *) printf 'Invalid option: "%s"\n' "$ch" ;;
     esac
   done
   exit "$EXIT"
 else
   exit 1
 fi
-
-# TODO: temp-cd to the git repo's root directory to perform the add.
-# TODO: find a way to choose which files to add.
diff --git a/local/bin/runnsend b/local/bin/runnsend
--- a/local/bin/runnsend
+++ b/local/bin/runnsend
@@ -7,8 +7,9 @@ source ~/.local/lib/ystd.sh
 depCheck notify-send
 
 commandStderr="$("$@" 2>&1 >/dev/null)"
+exitCode="$?"
 
-if [ $? != 0 ]; then
-  headingMessage="$(printf 'Error while running # %s' "$*")"
+if [ "$exitCode" = 0 ]; then
+  headingMessage="$(printf 'Error while running # [%s] %s' "$exitCode" "$*")"
   notify-send "$headingMessage" "$commandStderr"
 fi
diff --git a/local/bin/sync-usbst b/local/bin/sync-usbst
--- a/local/bin/sync-usbst
+++ b/local/bin/sync-usbst
@@ -3,31 +3,27 @@
 # A simple script to sync some things from my USB station (local to actual USB)
 # I still have to explain this.
 
-PROG="$(basename "$0")"
-
-for prog in rsync; do
-  if ! type "$prog" >/dev/null 2>/dev/null; then
-    echo "$PROG: $prog not found."
-    exit 1
-  fi
-done
+source ~/.local/lib/ystd.sh
+depCheck rsync fd
 
 if [ -z "$F_USB_STATION" ]; then
-  echo "$PROG: \$F_USB_STATION not found. Please set it with the path of the usb-station."
+  printf >&2 "%s\n" 'Variable \$F_USB_STATION not found'
   exit 1
-fi
-
-if [ -z "$F_DOTFILES" ]; then
-  echo "$PROG: \$F_DOTFILES not found. Please set it."
+elif [ -z "$DOTFILES" ]; then
+  printf >&2 "%s\n" 'Variable \$DOTFILES not found'
   exit 1
 fi
 
 mkdir -p "$F_USB_STATION/config/nvim"
-rsync -rtuvc --delete "$F_DOTFILES/config/nvim/" "$F_USB_STATION/config/nvim"
+rsync -rtuvc --delete "$DOTFILES/config/nvim/" \
+  "$F_USB_STATION/config/nvim"
 
-if rsync -rtuvc --delete "$HOME/.cache/nvim-plugs/" "$F_USB_STATION/config/nvim/bundle" && [ -n "$USB_STATION_REMOVE_GIT" ]; then
-  find "$F_USB_STATION/config/nvim/bundle" -mindepth 1 -maxdepth 1 -type d |
-    while read plugin; do
+if rsync -rtuvc --delete "$HOME/.cache/nvim-plugs/" \
+  "$F_USB_STATION/config/nvim/bundle" \
+  && [ -n "$USB_STATION_REMOVE_GIT" ]
+then
+  fd . "$F_USB_STATION/config/nvim/bundle" -t d -d 1 \
+    | while read plugin; do
       for file in .git .gitignore .github; do
         if [ -r "$plugin/$file" ]; then
           rm -rf "$plugin/$file"
