Modifications to git-check

diff --git a/local/bin/git-check b/local/bin/git-check
--- a/local/bin/git-check
+++ b/local/bin/git-check
@@ -1,42 +1,38 @@
 #!/usr/bin/env bash
 
-case $# in
-    0) repo_dir="${PWD}" ;;
-    1) repo_dir="${1}" ;;
-    *) echo "$0: invalid amount of args." ;;
-esac
+if [ $# != 1 ]; then
+  echo "Usage: $(basename $0) <repo-path>"
+  exit 1
+fi
 
-if (cd "${repo_dir}" && git status -sb); then
-    cd "${repo_dir}" 2>/dev/null
-    echo -e '\033[2 q'
-    while [ -z "${EXIT}" ]; do
-        echo -e "\e[33mCommands:\e[m [d]iff, [a]dd-commit, [p]ull, pu[s]h, [f]etch, [l]og, [q]uit"
-        printf "       λ> "
-        read -n1 ch
-        case "${ch}" in
-            d)
-                git add .
-                git diff HEAD
-                ;;
-            a)
-                git add . &&
-                    git commit ||
-                    git reset .
-                ;;
-            l) git log --all --oneline ;;
-            p) git pull ;;
-            s) git push ;;
-            f) git fetch ;;
-            "") EXIT=1 ;;
-            q) EXIT=1 ;;
-            ) EXIT=1 ;;
-            "") clear ;;
-            *) echo "Invalid option: \"${ch}\"." ;;
-        esac
-    done
-    echo; exit "${EXIT}"
+cd "$1" || exit
+
+if git status -sb; then
+  echo -e '\e[2 q'
+  while [ -z "$EXIT" ]; do
+    echo -e '\e[33mCommands:\e[m [d]iff, [a]dd-commit, [p]ull, pu[s]h, [f]etch, [l]og, [q]uit'
+    printf " (git) λ> "
+    read -n1 ch; echo
+    case "$ch" in
+      d)
+        git add .
+        git diff HEAD
+        ;;
+      a) git add . && git commit || git reset . ;;
+      l) git log --all --oneline ;;
+      p) git pull ;;
+      s) git push ;;
+      f) git fetch ;;
+      "") EXIT=0 ;;
+      q) EXIT=0 ;;
+      ) EXIT=0 ;;
+      "") clear ;;
+      *) echo "Invalid option: \"${ch}\"." ;;
+    esac
+  done
+  exit "$EXIT"
 else
-    exit 1
+  exit 1
 fi
 
 # TODO: temp-cd to the git repo's root directory to perform the add.
