Lemonbar & Stalonetray
* Sxhkd, Bspwm, Polybar, Script#start-lemonbar: started
using lemonbar and adjusted config accordingly. I also changed some
things on polybar's config before hopping out.

* Script#start-polybar: improved logging, similar to start-sxhkd.

* Stalonetray: I'm now using it because lemonbar has no support for
tray. Still adjusting some things but it seems okay. I'm toggling it
with super + t (as specified in sxhkd).

* Script#redscr: red screen manager.

* Nvim: added Surround() function and a failed prototype of the tex
filetype.

diff --git a/local/bin/start-polybar b/local/bin/start-polybar
--- a/local/bin/start-polybar
+++ b/local/bin/start-polybar
@@ -5,8 +5,12 @@
 source ~/.local/lib/ystd.sh
 depCheck polybar mktemp
 
-tmp="$(mktemp)"
-logfile="$tmp.polybar"
+tempLog="$(mktemp "/tmp/polybar.log.XXXXXXXX")"
+
+if [ -z "$tempLog" ]; then
+  printf >&2 "Could not generate temp file."
+  exit 1
+fi
 
 # Terminate already running polybar instances
 killall -q polybar
@@ -17,4 +21,4 @@ while pgrep -u $UID -x polybar >/dev/null; do
 done
 
 # Launch polybar
-polybar main 2>"$logfile"
+polybar main >"$tempLog" 2>"$tempLog"
