Lots of changes
I've renamed a bunch of scripts, removed some old files and added some
more environment variables. I want to make these scripts more
configurable later, so I think some nnn-like environment variable
configurations is cool.

diff --git a/local/bin/sync-usbst b/local/bin/sync-usbst
--- a/local/bin/sync-usbst
+++ b/local/bin/sync-usbst
@@ -4,10 +4,10 @@
 # I still have to explain this.
 
 for prog in rsync; do
-    if ! type $prog >/dev/null 2>/dev/null; then
-        echo "error: ${prog} not found."
-        exit 1
-    fi
+  if ! type $prog >/dev/null 2>/dev/null; then
+    echo "error: ${prog} not found."
+    exit 1
+  fi
 done
 
 USB_STATION="${USB_STATION:-/mnt/usb-main/usb-station}"
