Autogen for stalonetray & dunstrc, Script#pp...
* Script#pp: (stolen from https://github.com/jhjn/pp) a small
preprocessor that is helping me with some config files.

* dunstrc and stalonetrayrc are now generated via the dotsync command,
with the help of Script#pp.

* Fixes to qutebrowser (didn't realize it wasn't loading custom themes
and instead falling back to the default).

* Minor changes to Script#{display-report, dotsync, gen-xres}.

* Added theme file (config/dots/theme.sh).

* Changed theme to Tomorrow Night (soon I'll be trying to change the
engine to support base16 conventions).

diff --git a/config/zsh/zshrc b/config/zsh/zshrc
--- a/config/zsh/zshrc
+++ b/config/zsh/zshrc
@@ -159,6 +159,16 @@ duplicate() { # {{{
     *) exit 1 ;;
   esac & disown
 } # }}}
+cd-to-file() { # {{{
+  [ $# = 1 ] || exit 1
+  if [ -f "$1" ]; then
+    cd "$(dirname "$1")"
+  elif [ -d "$1" ]; then
+    cd "$1"
+  else
+    printf >&2 "cd-to-file: invalid file\n"
+  fi
+} # }}}
 
 shell::reload() { source "${ZDOTDIR:-$HOME}/.zshrc"; }
 xorg::log() { less "$XLOG"; }
@@ -170,6 +180,7 @@ alias \
   n='nnn-explore' \
   f='find-file' \
   fof='find-file openfork' \
+  fcd='find-file cd-to-file' \
   d='duplicate'
 alias rl='shell::reload'
 alias xlog='xorg::log'
