zsh: simplify some things in the zshrc

diff --git a/config/zsh/zshrc b/config/zsh/zshrc
--- a/config/zsh/zshrc
+++ b/config/zsh/zshrc
@@ -167,6 +167,7 @@ bindkey '^F' _bind_fzselect
 zle -N _bind_fzselect
 
 bindkey -s '^[w' '\eS w\n'
+bindkey -s '^[-' '\eS cd ..\n'
 
 lfAndCd() {
   local tmp=$(mktemp)
@@ -260,18 +261,6 @@ alias Dgui='dup-term-gui'
 alias Dtmux='dup-term-tmux'
 alias D='dup-term-auto'
 
-cdNearFile() {
-  [ $# = 1 ] || exit 1
-
-  if [ -f "$1" ]; then
-    cd "$(dirname "$1")"
-  elif [ -d "$1" ]; then
-    cd "$1"
-  else
-    printf >&2 "%s: invalid file\n" "$0"
-  fi
-}
-
 pushShell() {
   if [ "$SHELL_STACK" ]; then
     SHELL_STACK="$SHELL_STACK.${1:-zsh}" zsh
@@ -298,30 +287,28 @@ alias fo='findFile open'
 alias fof='findFile openfork'
 alias fcd='FINDFILE_DIRONLY=1 findFile cd-to-file'
 
-## a crappy version of make that tries to find the file on parent directories
-## if it's not on the current one.
-make() {
-  local dir
+anyArgIs() {
+  for arg in "${@:2}"; do
+    [ "$arg" = "$1" ] && return 0 || true
+  done
+  return 1
+}
 
-  if [ "$1" = "-f" ]; then
-    # a *very* crappy workaround for using `make -f`.
-    printf >&2 '[Warning] `-f` argument detected, running normal make\n'
+## A wrapepr around `make` that attempts to find the file on
+## parent directories if it's not on the current one.
+make() {
+  if anyArgIs "-f" "$@"; then
+    printf >&2 'info: `-f` argument detected, running normal make\n'
     command make "$@"
   else
-    dir="$PWD"
-    while true; do
-      if [ "$dir" = "/" ]; then
-        printf >&2 '[Error] Could not find any valid Makefile.\n'
-        return 1
-      fi
-
-      if [ -f "$dir/Makefile" ] || [ -f "$dir/makefile" ] || [ -f "$dir/GNUmakefile" ]; then
-        (cd "$dir" && command make "$@")
-        return $?
-      fi
-
-      dir=$(realpath -m "$dir/..")
-    done
+    dir=$(upfind 'Makefile') \
+      || dir=$(upfind 'makefile') \
+      || dir=$(upfind 'GNUmakefile') \
+      || {
+      printf >&2 "error: could not find any valid makefile...\n"
+      return 1
+    }
+    (cd "$dir" && command make "$@")
   fi
 }
 
@@ -332,7 +319,7 @@ alias g='git-check'
 alias G='tig status'
 
 alias p3='python3'
-alias pip='python3 -m pip'
+pip() { python3 -m pip "$@"; }
 
 alias sy='dotsync'
 alias of='openfork'
@@ -348,10 +335,6 @@ elif exists vim; then
   alias vi='vim'
 fi
 
-alias grep='grep --color=auto'
-alias fgrep='fgrep --color=auto'
-alias egrep='egrep --color=auto'
-
 # A wrapper for the `info` command
 info() {
   printf "\033[2 q"
@@ -363,7 +346,7 @@ sourceOneOf \
   /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh
 
 _ept_canonicalize_str() {
-  test $# = 1 || return 1
+  [ $# = 1 ] || return 1
 
   case "$1" in
     pt|br) printf "pt-br" ;;
@@ -504,6 +487,12 @@ tbw() {
   printf >&2 "NVME:\n"
   sudo -n nvme smart-log /dev/nvme0 | grep 'Data Units Written'
 }
+
+venv-python() {
+  local _path="$(upfind venv)" || return 1
+  "$_path/venv/bin/python" "$@"
+}
+alias vp='venv-python'
 
 _fm_run() {
   "$@"
