Better zsh bookmarks and some patches
So, I finally did a better bookmarking system. It uses fzagnostic to
select a directory or file, and is run via functions on zsh.

Current sources are projects (in $PROJECTS) and bookmarks (in
$DIR_BOOKMARKS file (eval-unsafe)).

diff --git a/scripts/dmenurun b/scripts/dmenurun
--- a/scripts/dmenurun
+++ b/scripts/dmenurun
@@ -1,10 +1,11 @@
 #!/usr/bin/env sh
 
-prog="$(pathbin | dmenu "$@")"
+choice="$(gen-pathbin | fzagnostic)" || exit 1
 
-if grep -q '!$' <<<"$prog"; then
-  prog="${prog%?}"
-  exec $TERMINAL -e "$prog"
+if printf "%s" "$choice" | grep -q '!$'; then
+  # choice ends with !, so it should be opened in a new instance
+  "$TERMINAL" -e "${choice%?}"
 else
-  exec "$prog"
+  # choice doesn't end with !, open silently
+  "$choice"
 fi
