improved setbg, ext and more; trying out terminal-only emacs

diff --git a/scripts/ext b/scripts/ext
--- a/scripts/ext
+++ b/scripts/ext
@@ -1,32 +1,42 @@
 #!/usr/bin/env sh
 
-# [Stolen from Lukesmithxyz/voidrice]
+# [Stolen from github.com/Lukesmithxyz/voidrice]
 # A general, all-purpose extraction script.
 
 # Default behavior: Extract archive into new directory
 # Behavior with `-c` option: Extract contents into current directory
 
-# showHelp() { # TODO: make help in this way
-#   printf >&2 "Usage: %s" "$(basename $0) [-c] <file>"
-# }
+PROGNAME=$(basename "$0")
 
-while getopts "hc" o; do case "$o" in
-  c) extracthere="True" ;;
-  *) printf "Options:\\n   -c: Extract archive into current directory rather than a new one.\\n" && exit ;;
-esac done
+shelp() {
+  printf >&2 "Usage: %s\n" "$PROGNAME [-c] ARCHIVE"
+  printf >&2 "Options:\n"
+  printf >&2 "  %s : %s\n" "-c" "Extract archive into current ditrectory rather than a new one."
+  exit 1
+}
+
+[ $# = 0 ] && shelp
+
+while getopts "hc" o; do
+  case "$o" in
+    c) extracthere="True" ;;
+    *) shelp ;;
+  esac
+done
 
 if [ -z "$extracthere" ]; then
-  archive="$(readlink -f "$*")" &&
-    directory="$(echo "$archive" | sed 's/\.[^\/.]*$//')" &&
-    mkdir -p "$directory" &&
-    cd "$directory" || exit
-    else
-      archive="$(readlink -f "$(echo "$*" | cut -d' ' -f2)")"
+  archive=$(readlink -f "$*") \
+    && [ -f "$archive" ] \
+    && directory=$(echo "$archive" | sed 's/\.[^\/.]*$//') \
+    && mkdir -p "$directory" \
+    && cd "$directory" || exit
+else
+  archive=$(readlink -f "$(echo "$*" | cut -d' ' -f2)")
 fi
 
-[ "$archive" = "" ] && printf "Give archive to extract as argument.\\n" && exit
+[ "$archive" = "" ] && printf "Give archive to extract as argument.\n" && exit
 
-if [ -f "$archive" ] ; then
+if [ -f "$archive" ]; then
   case "$archive" in
     *.tar.bz2|*.tar.xz|*.tbz2) tar xvjf "$archive" ;;
     *.tar.gz|*.tgz) tar xvzf "$archive" ;;
@@ -40,8 +50,8 @@ if [ -f "$archive" ] ; then
     *.7z) 7z x "$archive" ;;
     *.xz) unxz "$archive" ;;
     *.exe) cabextract "$archive" ;;
-    *) printf "extract: '%s' - unknown archive method\\n" "$archive" ;;
+    *) printf "extract: \"%s\" - unknown archive method\n" "$archive" ;;
   esac
 else
-  printf "File \"%s\" not found.\\n" "$archive"
+  printf "File \"%s\" not found.\n" "$archive"
 fi
diff --git a/scripts/setbg b/scripts/setbg
--- a/scripts/setbg
+++ b/scripts/setbg
@@ -1,16 +1,43 @@
 #!/usr/bin/env sh
 
 if [ $# != 0 ]; then
-  printf >&2 "%s\n" "Usage: $(basename $0)"
+  printf >&2 "Usage: %s\n" "$(basename $0)"
+  printf >&2 "Environment variables used:\n"
+  printf >&2 "  %s : %s\n" "SETBG_IMG_DIR" "The directory where the wallpapers are located (if image)"
+  printf >&2 "  %s : %s\n" "SETBG_WALLPAPER_TYPE" "The type of background to be set."
+  printf >&2 "   : %s\n" "color -> use hsetroot to set background to 'root.background' resource"
+  printf >&2 "   : %s\n" "{ image | img } -> use feh to set background image (see SETBG_WALLPAPER_DIR)"
   exit 1
 fi
 
-if [ -z "$SETBG_WALLPAPER_DIR" ]; then
-  printf >&2 "Please set %s to the wallpapers folder path\n" '$SETBG_WALLPAPER_DIR'
-  exit 1
-fi
+case "$SETBG_WALLPAPER_TYPE" in
+  image|img)
+    if [ -z "$SETBG_IMG_DIR" ]; then
+      printf >&2 "Please set %s to the wallpapers folder path\n" '$SETBG_WALLPAPER_DIR'
+      exit 1
+    fi
 
-image="$(shuf -n1 -e "$SETBG_WALLPAPER_DIR"/"$SETBG_THEME"/*.jpg)" # there's no problem if SETBG_THEME is unset, since it would evaluate to simply the wallpapers path.
-feh --no-fehbg --bg-fill "$image"
+    if [ -d "$SETBG_IMG_DIR" ]; then
+      printf >&2 "Image dir %s doesn't exist.\n" "$SETBG_IMG_DIR"
+      exit 1
+    fi
 
-# hsetroot -solid "$(xgetres root.background)" -brightness -0.05
+    image=$(shuf -n1 -e "$SETBG_IMG_DIR"/*) || exit 1
+    feh --no-fehbg --bg-fill "$image" || exit 1
+    ;;
+  color)
+    xresource="root.background"
+    color=$(xgetres "$xresource") || {
+      printf >&2 "Could not get X resource '%s'\n" "$xresource"
+      exit 1
+    }
+    hsetroot -solid "$color" -brightness -0.05
+    ;;
+  *)
+    printf >&2 "Invalid wallpaper type: %s\n" "$SETBG_WALLPAPER_TYPE"
+    exit 1
+    ;;
+esac
+
+
+
