feat(wayland): WAYLAND!!! + river
Backlight, audio and dbus are wonky right now. Help me

diff --git a/scripts/fzpow b/scripts/fzpow
--- a/scripts/fzpow
+++ b/scripts/fzpow
@@ -1,4 +1,4 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 # vim: fdm=marker
 
 # A simple script for power actions.
@@ -49,11 +49,28 @@ showHelp() {
   printf >&2 "%s\n" "If no argument is specified, a fzagnostic pop-up is shown to select it manually."
 }
 
+isWayland() { [ "$WAYLAND_DISPLAY" ]; }
+isXorg() { ! isWayland && [ "$DISPLAY" ]; }
+
 action_lock() {
-  if exists bslock; then
+  _getWaylockColors() {
+    c_init="0x$(dotcfg-client get theme_no_prefix.base01)" || return 1
+    c_input="0x$(dotcfg-client get theme_no_prefix.base03)" || return 1
+    c_fail="0x$(dotcfg-client get theme_no_prefix.base0F)" || return 1
+  }
+
+  if isXorg && exists bslock; then
     _lock() { bslock; }
-  elif exists betterlockscreen; then
+  elif isXorg && exists betterlockscreen; then
     _lock() { betterlockscreen -l; }
+  elif isWayland && exists waylock; then
+    if _getWaylockColors; then
+      waylock_args=(-init-color "$c_init" -input-color "$c_input" -fail-color "$c_fail")
+    else
+      waylock_args=()
+    fi
+
+    _lock() { waylock "${waylock_args[@]}"; }
   else
     printf >&2 "No lockscreen program found.\n"
     return 1
@@ -72,7 +89,8 @@ action_lock() {
 
   # if it's been more than 5 seconds since the lockscreen spawned and it died from an error, then shut down the system for security reasons
   elif [ $(($end_time - $start_time)) -gt 5 ]; then
-    systemctl poweroff
+    notify-send "SHOULD POWEROFF"
+    # systemctl poweroff
   fi
 }
 
diff --git a/scripts/setbg b/scripts/setbg
--- a/scripts/setbg
+++ b/scripts/setbg
@@ -1,12 +1,32 @@
 #!/usr/bin/env sh
 
+set -x
+
 if [ $# != 0 ]; then
   printf >&2 "Usage: %s\n" "$(basename $0)"
   printf >&2 "Control is done via the following environment variables:\n"
   printf >&2 " %s : %s\n" "SETBG_IMG_DIR" "The directory where the wallpapers are located (if image)"
   printf >&2 " %s : %s\n" "SETBG_WALLPAPER_TYPE" "The type of background to be set."
-  printf >&2 "    -> %s\n" "color -> use hsetroot to set background to 'root.background' resource"
+  printf >&2 "    -> %s\n" "color -> set background to 'root.background' resource"
   printf >&2 "    -> %s\n" "{ image | img } -> set background image (see SETBG_IMG_DIR)"
+  exit 1
+fi
+
+if [ "$WAYLAND_DISPLAY" ]; then
+  killOld() { pkill swaybg; }
+  setImg() {
+    killOld
+    swaybg -i "$1" & disown
+  }
+  setColor() {
+    killOld
+    swaybg -c "$1" & disown
+  }
+elif [ "$DISPLAY" ]; then
+  setImg() { hsetroot -extend "$1" -tint "#BBB"; }
+  setColor() { hsetroot -solid "$1" -brightness -0.05; }
+else
+  printf >&2 "Neither Wayland nor X11 was detected; aborting\n"
   exit 1
 fi
 
@@ -27,14 +47,14 @@ case "$SETBG_WALLPAPER_TYPE" in
     fi
 
     image=$(shuf -n1 -e "$SETBG_IMG_DIR"/*) || exit 1
-    hsetroot -extend "$image" -tint "#BBB" || exit 1
+    setImg "$image" || exit 1
     ;;
   color)
     color=$(dotcfg-client get theme.base01) || {
       printf >&2 "Could not get X resource '%s'\n" "$xresource"
       exit 1
     }
-    hsetroot -solid "$color" -brightness -0.05
+    setColor "$color" || exit 1
     ;;
   *)
     printf >&2 "Invalid wallpaper type: %s\n" "$SETBG_WALLPAPER_TYPE"
