refactor(gen-config): much more modular design

diff --git a/scripts/gen-config b/scripts/gen-config
--- a/scripts/gen-config
+++ b/scripts/gen-config
@@ -1,31 +1,73 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 
 . "$DOTFILES/config/dots/env.sh"
 eval "$(load-base16-theme --export)"
 
+pname=$(basename "$0")
+
+main() {
+  ALL=(_init stalonetray dunst gtk3 foot yambar wget termux)
+  [ $# = 0 ] && targets=("${ALL[@]}")
+  [ $# -gt 0 ] && targets=(_init "$@")
+  [ $# = 1 ] && [ "$1" = all ] && targets=("${ALL[@]}")
+
+  for t in "${targets[@]}"; do
+    fn_name="_t_$t"
+    if declare -f "$fn_name" >/dev/null; then
+      printf >&2 "%s: running target %s\n" "$pname" "$t"
+      eval "$fn_name"
+    else
+      printf >&2 "%s: could not find target %s; skipping\n" "$pname" "$t"
+    fi
+  done
+}
+
 gen() {
-  printf >&2 "Generating target: %s\n" "$2"
   mkdir -p "$(dirname "$2")"
   pp "$1" > "$2"
 }
 
-mkdir -p "$XDG_CACHE_HOME/gen"
-gen "$DOTFILES/config/gen/stalonetrayrc" "$XDG_CACHE_HOME/gen/stalonetrayrc"
-gen "$DOTFILES/config/gen/dunstrc" "$XDG_CACHE_HOME/gen/dunstrc"
-gen "$DOTFILES/config/gen/gtk3rc" "$XDG_CONFIG_HOME/gtk-3.0/settings.ini"
-gen "$DOTFILES/config/gen/foot.ini" "$XDG_CONFIG_HOME/foot/foot.ini"
-gen "$DOTFILES/config/gen/yambar.yml" "$XDG_CONFIG_HOME/yambar/config.yml"
+_t__init() {
+  mkdir -p "$XDG_CACHE_HOME/gen"
+}
 
-for i in 2 3; do
-  _ln_dir="$HOME/.themes/dummy"
-  _flatcolor_dir="$HOME/.themes/FlatColor"
+_t_stalonetray() {
+  gen "$DOTFILES/config/gen/stalonetrayrc" "$XDG_CACHE_HOME/gen/stalonetrayrc"
+}
 
-  gen "$DOTFILES/config/gen/gtk-flatcolor-${i}.0" "$_flatcolor_dir/colors${i}"
-  [ ! -d "$_ln_dir" ] && ln -s "$_flatcolor_dir" "$_ln_dir"
-done
+_t_dunst() {
+  gen "$DOTFILES/config/gen/dunstrc" "$XDG_CACHE_HOME/gen/dunstrc"
+}
 
-[ "$WGETRC" ] && printf "hsts-file = %s" "$XDG_CACHE_HOME/wget-hsts" >"$WGETRC"
+_t_gtk3() {
+  gen "$DOTFILES/config/gen/gtk3rc" "$XDG_CONFIG_HOME/gtk-3.0/settings.ini"
 
-if [ -d ~/.termux ]; then
-  gen "$DOTFILES/config/gen/termux-colors" ~/.termux/colors.properties
-fi
+  # TODO: not working i think
+  # for i in 2 3; do
+  #   _ln_dir="$HOME/.themes/dummy"
+  #   _flatcolor_dir="$HOME/.themes/FlatColor"
+
+  #   gen "$DOTFILES/config/gen/gtk-flatcolor-${i}.0" "$_flatcolor_dir/colors${i}"
+  #   [ ! -d "$_ln_dir" ] && ln -s "$_flatcolor_dir" "$_ln_dir"
+  # done
+}
+
+_t_foot() {
+  gen "$DOTFILES/config/gen/foot.ini" "$XDG_CONFIG_HOME/foot/foot.ini"
+}
+
+_t_yambar() {
+  gen "$DOTFILES/config/gen/yambar.yml" "$XDG_CONFIG_HOME/yambar/config.yml"
+}
+
+_t_wget() {
+  [ "$WGETRC" ] && printf "hsts-file = %s" "$XDG_CACHE_HOME/wget-hsts" >"$WGETRC"
+}
+
+_t_termux() {
+  if [ -d ~/.termux ]; then
+    gen "$DOTFILES/config/gen/termux-colors" ~/.termux/colors.properties
+  fi
+}
+
+main "$@"
