feat[vim]: visual line movement; feat[install-zig.sh]...

diff --git a/scripts/rifle-run b/scripts/rifle-run
--- a/scripts/rifle-run
+++ b/scripts/rifle-run
@@ -5,16 +5,13 @@
 
 . "$(uselib std)"
 
+set -e
+
 if [ $# != 3 ]; then
   printf >&2 "Usage: %s\n" "$(basename $0) <ACTION> <FILETYPE> <FILENAME>"
   printf >&2 "The ACTION and FILETYPE fields are handled based on the code of this script.\n"
   exit 1
 fi
-
-tmp=$(mktemp) || {
-  printf >&2 "Could not generate temp file.\n"
-  exit 1
-}
 
 if [ -z "$3" ]; then
   printf >&2 "Empty filename.\n"
@@ -23,10 +20,12 @@ else
   file=$(realpath -m "$3") || exit 1
 fi
 
-printf >&2 "@[TEMP DIR: %s]\n\n" "$tmp"
-rm -f "$tmp" # remove temp file for preventing any errors related to "file already exists"
+tmp=$(mktemp -d) || {
+  printf >&2 "Could not generate temp file.\n"
+  exit 1
+}
 
-set -e
+printf >&2 "@[TEMP DIR: %s]\n\n" "$tmp"
 
 cleanup() {
   [ -d "$tmp" ] && rm -r "$tmp"
@@ -151,7 +150,7 @@ case "$1" in
       scheme) guile "$file" ;;
       latex|tex)
         name=$(basename "${file%.*}")
-        pdflatex -output-directory "$tmp" "$file"
+        pdflatex -output-directory "$tmp" "$file" </dev/null
         OPEN_GUI=1 open "$tmp/$name.pdf"
         ;;
       python)
@@ -170,6 +169,7 @@ case "$1" in
       html) openfork "$file" ;;
       moon) moon "$file" ;;
       zig) zig run "$file" --color off --cache-dir "$tmp" ;;
+      fennel) fennel "$file" ;;
       *) die '(action "%s") unhandled filetype: %s\n' "$1" "$2" ;;
     esac ;;
   build)
