misc: small changes

diff --git a/scripts/rifle-run b/scripts/rifle-run
--- a/scripts/rifle-run
+++ b/scripts/rifle-run
@@ -214,6 +214,14 @@ case "$1" in
           exit 1
         fi
         ;;
+      typescript)
+        if exists deno; then
+          deno run "$file"
+        else
+          printf >&2 "Could not find a known TS interpreter.\n"
+          exit 1
+        fi
+        ;;
       java)
         printf >&2 "[ Warning ] the class with the main method needs to be 'Main'\n" # TODO: fix this limitation
         cd "$tmp"
