refactor: used shellcheck to check&fix scripts

diff --git a/scripts/runnsend b/scripts/runnsend
--- a/scripts/runnsend
+++ b/scripts/runnsend
@@ -2,7 +2,7 @@
 
 # Runs a command, and sends a notification based if a condition matches.
 
-. "$(uselib std)"
+exists() { command -v "$1" >/dev/null 2>/dev/null; }
 
 if exists notify-send; then
   nsend() { notify-send -- "$1" "$2"; }
@@ -13,8 +13,10 @@ else
   depCheck notify-send termux-notification
 fi
 
+PROGNAME=$(basename "$0")
+
 if [ $# -lt 2 ]; then
-  printf >&2 "%s\n" "Usage: $(basename $0) <NOTIFY-IF> <PROGRAM> [ARGS...]"
+  printf >&2 "%s\n" "Usage: $PROGNAME <NOTIFY-IF> <PROGRAM> [ARGS...]"
   printf >&2 "%s\n" "where NOTIFY-IF := { error-and-output | error-or-output | error | output }"
   exit 1
 fi
@@ -27,7 +29,7 @@ case "$notifyIf" in
   error-or-output) ;;
   error|output) ;;
   *)
-    printf >&2 "Invalid option; use $(basename $0) --help\n"
+    printf >&2 "Invalid option; use %s --help\n" "$PROGNAME"
     exit 1
     ;;
 esac
diff --git a/scripts/setbg b/scripts/setbg
--- a/scripts/setbg
+++ b/scripts/setbg
@@ -1,7 +1,7 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 
 if [ $# != 0 ]; then
-  printf >&2 "Usage: %s\n" "$(basename $0)"
+  printf >&2 "Usage: %s\n" "$(basename "$0")"
   printf >&2 "Control is done via the following environment variables:\n"
   printf >&2 " %s : %s\n" "SETBG_IMG_DIR" "The directory where the wallpapers are located (if image)"
   printf >&2 " %s : %s\n" "SETBG_WALLPAPER_TYPE" "The type of background to be set."
@@ -49,7 +49,7 @@ case "$SETBG_WALLPAPER_TYPE" in
     ;;
   color)
     color=$(dotcfg send get:theme.base01) || {
-      printf >&2 "Could not get X resource '%s'\n" "$xresource"
+      printf >&2 "Failed to get background color\n"
       exit 1
     }
     setColor "$color" || exit 1
diff --git a/scripts/winew b/scripts/winew
--- a/scripts/winew
+++ b/scripts/winew
@@ -6,7 +6,7 @@ WINEW_32_PREFIX="${WINEW_32_PREFIX:-$XDG_DATA_DIR/wine32}"
 WINEW_64_PREFIX="${WINEW_64_PREFIX:-$XDG_DATA_DIR/wine64}"
 XDG_DATA_DIR="${XDG_DATA_DIR:-$HOME/.local/share}"
 
-PROGNAME=$(basename $0)
+PROGNAME=$(basename "$0")
 
 usage() {
   printf >&2 "Usage: %s\n" "$PROGNAME { open <BIN> [ARGS...] | cmd | cfg | add-recent <BIN> | tricks <ARGS...> | server [ARGS...] | fwd [ARGS...] | desktop [ARGS...] }"
@@ -18,11 +18,11 @@ usage() {
 
 has_line() {
   if [ $# != 1 ]; then
-    printf >&2 "%s: invalid amount of arguments\n" "$(basename $0)"
+    printf >&2 "%s: invalid amount of arguments\n" "$PROGNAME"
     return 1
   fi
 
-  while read line; do
+  while read -r line; do
     [ "$line" = "$1" ] && return 0
   done
 
@@ -76,7 +76,7 @@ case "$1" in
     exit
     ;;
   desktop)
-    resolution=$(xrandr | grep '*' | awk '{print $1}') || resolution=800x600
+    resolution=$(xrandr | awk '/\*/ { print $1 }') || resolution=800x600
     shift; launch_shell wine explorer /desktop=shell,"$resolution" "$@"
     exit
     ;;
