x/wayland init config

diff --git a/scripts/start-xserver b/scripts/start-xserver
--- a/scripts/start-xserver
+++ b/scripts/start-xserver
@@ -1,17 +1,20 @@
 #!/usr/bin/env sh
 
 # starts an X server
-# TODO: add support for Xephyr
+
+progname=$(basename "$0")
 
 calc() { printf "%s\n" "$1" | bc; }
 
+default_initrc="${XDG_CONFIG_HOME:-$HOME/.config}/xorg/xinitrc"
+
 case $# in
-  0) initrc="${XDG_CONFIG_HOME:-$HOME/.config}/xorg/initrc" ;;
+  0) initrc="$default_initrc" ;;
   1) initrc="$1" ;;
   2)
-    printf >&2 "%s: invalid amount of argument\n" "$(basename "$0")"
-    printf >&2 "Usage: %s\n" "$(basename "$0") [INITRC]"
-    printf >&2 "INITRC defaults to %s if not specified.\n" '$XDG_CONFIG_HOME/xorg/initrc'
+    printf >&2 "%s: invalid amount of arguments\n" "$progname"
+    printf >&2 "Usage: %s [INITRC]\n" "$progname"
+    printf >&2 "INITRC defaults to %s if not specified.\n" "$default_initrc"
     exit 1
     ;;
 esac
@@ -22,7 +25,7 @@ if [ ! -f "$initrc" ] || [ ! -r "$initrc" ]; then
 fi
 
 if [ "$DISPLAY" ] && [ -z "$USE_XEPHYR" ]; then
-  printf >&2 "%s is set, an X server is probably already running; aborting\n" '$DISPLAY'
+  printf >&2 '$DISPLAY is set, an X server is probably already running; aborting\n'
   exit 1
 fi
 
