Remade script#start-xserver

diff --git a/scripts/start-xserver b/scripts/start-xserver
--- a/scripts/start-xserver
+++ b/scripts/start-xserver
@@ -1,24 +1,38 @@
 #!/usr/bin/env sh
 
-printf >&2 "%s\n" \
-  "Start time: $(date +"%Y/%m/%d %H:%M:%S")"
+source ~/.local/lib/ystd.sh
+depCheck startx
 
 if [ -n "$DISPLAY" ]; then
   printf >&2 "%s\n" "DISPLAY is set, an x server is probably already running; aborting..."
   exit 1
 fi
 
+case $# in
+  0)
+    standardInit="${XDG_CONFIG_HOME:-$HOME/.config}/xorg/initrc"
+    [ -f "$standardInit" ] && initrc="$standardInit" || initrc="$HOME/.xinitrc"
+    ;;
+  1)
+    initrc="$1"
+    ;;
+  2)
+    printf >&2 "%s\n" "$(basename $0): invalid amount of arguments"
+    printf >&2 "%s\n" "Usage: $(basename $0) [init_file]"
+    printf >&2 "%s\n" "init_file defaults to \$XDG_CONFIG_HOME/xorg/initrc or ~/.xinitrc."
+    exit 1
+    ;;
+esac
+
 logfile="$(mktemp /tmp/xorg.XXXXXXXX)"
-
-printf >&2 "Log file: " "$logfile"
-printf "%s" "$logfile"
-printf >&2 "\n"
-
 export XLOG="$logfile"
-startx >"$logfile" 2>"$logfile"
+
+printf >&2 "Start time: %s\n" "$(date +"%Y/%m/%d %H:%M:%S")"
+printf >&2 "Log file: %s\n" "$logfile"
+
+startx "$initrc" >"$logfile" 2>"$logfile"
 exitCode="$?"
 
-printf >&2 "%s\n" \
-  "End time: $(date +"%Y/%m/%d %H:%M:%S")"
+printf >&2 "End time: %s\n" "$(date +"%Y/%m/%d %H:%M:%S")"
 
-exit "$?"
+exit "$exitCode"
