Some patches and lfcd

diff --git a/scripts/uselib b/scripts/uselib
--- a/scripts/uselib
+++ b/scripts/uselib
@@ -23,5 +23,5 @@ for libfolder in "$DOTFILES/lib" "$HOME/.local/lib"; do
   fi
 done
 
-printf >&2 "Could not find library.\n"
+printf >&2 'Could not find library: "%s".\n' "$LIBNAME"
 exit 1
